services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "8899:8080"
    environment:
      - PASSWORD=1qaz@WSX
      - ADMINPASSWORD=1qaz@WSX
    volumes:
      - /www/wwwroot/tv.shanke5589.dpdns.org:/app
    restart: unless-stopped
